### PR TITLE
Mvp+1

### PR DESCRIPTION
**Pull request by phiden**
User editing forms functional.

### CODE REVIEW

**Comment by ErnieAtLYD** [comment]
FYI, I've moved development from manage-users.html to a different template. Ping me in the morning.

**Comment by phiden** [comment]
Yeah, I saw it -- manage/users, yes?

**Comment by ErnieAtLYD** [comment]
URL will be at `/users/manage`, template will be at `/user/manage.html`.

**Comment by phiden** [comment]
Ok. I'll start integration of mine with that tomorrow.

**Pull request merged**
